apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactsapi
  template:
    metadata:
      labels:
        app: contactsapi
    spec:
      containers:
        - name: web
          image: your-docker-image:latest
          command:
            [
              "pipenv",
              "run",
              "gunicorn",
              "contactsapi.wsgi:application",
              "--bind",
              "0.0.0.0:8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET_KEY
              value: "JWT_SECRET_KEYJWT_SECRET_KEYJWT_SECRET_KEYJWT_SECRET_KEYJWT_SECRET_KEYJWT_SECRET_KEYJWT_SECRET_KEY"
          volumeMounts:
            - name: app-volume
              mountPath: /app
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: app-volume
          hostPath:
            path: /path/to/your/app
            type: Directory
